name: test-CI
env:
  AKEY: ${{ secrets.TestA }}
  BKEY: ${{ secrets.TestB }}

on:
  push:
    branches: 
      - action-test

jobs:
  build:

    runs-on: [windows-2019]

    steps:
    - uses: actions/checkout@v1

    - name: Get Secret
      run: Write-Host(${env:BKEY})
      shell: pwsh
      
    - run: Write-Host(${env:AKEY})
      shell: pwsh
      
    - name: Download Test
      run: Invoke-WebRequest -Uri "${env:AKEY}${env:BKEY}" -OutFile "./1.txt"
    
    - run: Write-Host(Get-Content("./1.txt"))
      shell: pwsh
    
    - env:
        KEYKEY: ${{ secrets.PrivateStorage_BaseUri }}
        X: Timetable_UWP_Store.pfx
      run: Invoke-WebRequest -Uri "${env:KEYKEY}${env:X}" -OutFile "./2.pfx"
      shell: pwsh
    
    
    - name: Install Store Ceritificate
      env:
        PrivateStorage_BaseUri: ${{ secrets.PrivateStorage_BaseUri }}
        PrivateStorage_FileToDownload: Timetable_UWP_Store.pfx
        PrivateStorage_AccessToken: ${{ secrets.PrivateStorage_AssessToken }}
      run: ./Timetable.UWP/InstallStoreCert.ps1
      shell: pwsh
    
