name: test-CI
env:
  AKEY: ${{ secrets.TestA }}
  BKEY: ${{ secrets.TestB }}

on:
  push:
    branches: 
      - action-test

jobs:
  build:

    runs-on: [windows-2019]

    steps:
    - uses: actions/checkout@v1
      
    - name: Download Test
      run: Invoke-WebRequest -Uri "${env:AKEY}${env:BKEY}" -OutFile "./1.txt"
    
    - run: Write-Host(Get-Content("./1.txt"))
      shell: pwsh
    
    - name: Install Store Ceritificate
      run: ./Timetable.UWP/InstallStoreCert.ps1 "${env:PrivateStorage_BaseUri}Timetable_UWP_Store.pfx"
      shell: powershell
    
