name: UWP CI

on: [push]

env:
  buildPlatform: x86|x64|ARM
  appxPackageDir: ./_appxPackage
  configuration: Release
  vsPlatform: x86

jobs:
  build:

    runs-on: [windows-2019]

    steps:
    - name: Check out repo
      uses: actions/checkout@v1

    - name: Setup VS Dev Environment
      uses: seanmiddleditch/gha-setup-vsdevenv@v1
      with: 
        components: Microsoft.VisualStudio.Workload.Universal;Microsoft.VisualStudio.Component.Windows10SDK.18362
    
    - name: Setup MSBuild
      uses: warrenbuckley/Setup-MSBuild@v1
      
    - name: Setup Nuget
      uses: warrenbuckley/Setup-Nuget@v1
      
    - name: Restore Nuget Packages
      run: nuget restore ./Timetable.UWP/Timetable.UWP.csproj -Recursive

    - name: Install Store Ceritificate
      run: ./Timetable.UWP/InstallStoreCert.ps1
      shell: pwsh
      with:
        PrivateStorage_BaseUri: ${{secrets.PrivateStorage_BaseUri}}
        PrivateStorage_FileToDownload: Timetable_UWP_Store.pfx
        PrivateStorage_AccessToken: ${{secrets.PrivateStorage_AssessToken}}
      
    - name: Build UWP Project
      run: 
        msbuild.exe ./Timetable.UWP/Timetable.UWP.csproj 
          /p:Platform="${env:vsPlatform}" 
          /p:Configuration="${env:configuration}" 
          /p:AppxBundlePlatforms="${env:buildPlatform}" 
          /p:AppxPackageDir="${env:appxPackageDir}" 
          /p:PackageCertificateKeyFile="${env:INPUT_StoreCertPassword}"
          /p:AppxBundle=Always /p:UapAppxPackageBuildMode=StoreUpload
      shell: pwsh
      with:
        StoreCertPassword: ${{secrets.CERT_KEY}}
      
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        path: ${{env.appxPackageDir}}/*
